exports.process = {
    name: ['master', 'server', 'schedule']
};
exports.env = {
    name: process.env.NAME,
    initialize: process.env.INITIALIZE,
    mgmt: process.env.MGMT,
    master: process.env.MASTER
};
exports.database = {
    name: 'storage',
    bin: '/usr/bin',
    dbpath: '/var/lib/mongo',
    logpath: '/var/log/mongodb/mongod.log',
    replicaSet: 'orcafs'
};
exports.log = {
    path: '/var/log/orcafs-gui.log',
    maxSize: 1024 * 1024 * 10,
    backup: 3
};
exports.cookie = {
    maxAge: 1000 * 60 * 60 * 24 * 7,
    overwrite: false,
    httpOnly: false,
    signed: false,
    rolling: true
};
exports.snapshot = {
    total: 64,
    manual: 25,
    auto: 39
};
exports.setting = {
    nodeList: 'NODE-LIST',
    initParam: 'INITIALIZE-PARAMETER',
    snapshotSetting: 'SNAPSHOT-SETTING'
};
exports.user = {
    name: 'admin',
    password: '123456',
    key: 'orcadt@xian'
};
exports.api = {
    server: {
        receiveevent: 'http://localhost/api/receiveevent'
    },
    orcafs: {
        gettoken: 'http://localhost:9090/token/get',
        listdisk: 'http://localhost:9090/disk/list/',
        createcluster: 'http://localhost:9090/cluster/create',
        createstatus: 'http://localhost:9090/cluster/createstatus',
        destroycluster: 'http://localhost:9090/cluster/destroy',
        getversion: 'http://localhost:9090/cluster/getversion',
        getstoragespace: 'http://localhost:9090/cluster/getstoragespace',
        listmetanodes: 'http://localhost:9090/cluster/listmetanodes',
        liststoragenodes: 'http://localhost:9090/cluster/liststoragenodes',
        listtargets: 'http://localhost:9090/cluster/listtargets',
        getclusteriostat: 'http://localhost:9090/cluster/getclusteriostat',
        listallnodes: 'http://localhost:9090/cluster/listallnodes',
        getnodeservice: 'http://localhost:9090/cluster/getnodeservice',
        getphysicresource: 'http://localhost:9090/cluster/getphysicresource',
        getiostat: 'http://localhost:9090/cluster/getiostat',
        listnodetargets: 'http://localhost:9090/cluster/listnodetargets',
        addmetanode: 'http://localhost:9090/cluster/addmetanode',
        addstoragenode: 'http://localhost:9090/cluster/addstoragenode',
        addmgmtnode: 'http://localhost:9090/cluster/addmgmtnode',
        addclientnode: 'http://localhost:9090/cluster/addclientnode',
        applysnapconf: 'http://localhost:9090/cluster/applysnapconf',
        listsnapshot: 'http://localhost:9090/cluster/listsnapshot',
        createsnapshot: 'http://localhost:9090/cluster/createsnapshot',
        deletesnapshot: 'http://localhost:9090/cluster/deletesnapshot',
        batchdeletesnap: 'http://localhost:9090/cluster/batchdeletesnap',
        rollbacksnapshot: 'http://localhost:9090/cluster/rollbacksnapshot',
        getclientlist: 'http://localhost:9090/cluster/getclientlist',
        nasmanager: 'http://localhost:9090/cluster/nasmanager',
        getshareinfo: 'http://localhost:9090/cluster/getshareinfo',
        addshareinfo: 'http://localhost:9090/cluster/addshareinfo',
        nfsmodifyshare: 'http://localhost:9090/cluster/nfsmodifyshare',
        nfsdeleteshare: 'http://localhost:9090/cluster/nfsdeleteshare',
        getclientinfo: 'http://localhost:9090/cluster/getclientinfo',
        addclientinfo: 'http://localhost:9090/cluster/addclientinfo',
        modifyclientinfo: 'http://localhost:9090/cluster/modifyclientinfo',
        nfsdeleteclient: 'http://localhost:9090/cluster/nfsdeleteclient',
        nascifssharemanager: 'http://localhost:9090/cluster/nascifssharemanager',
        nasusermanager: 'http://localhost:9090/cluster/nasusermanager',
        addstoragetarget: 'http://localhost:9090/cluster/addstoragetarget',
        listmirrorgroup: 'http://localhost:9090/cluster/listmirrorgroup',
        createbuddymirror: 'http://localhost:9090/cluster/createbuddymirror',
        getfiles: 'http://localhost:9090/cluster/getdirs',
        entryinfo: 'http://localhost:9090/cluster/getentryinfo',
        setpattern: 'http://localhost:9090/cluster/setpattern'
    }
};
exports.key = {
    testapi: 'c40b0c360f3d4959b53b103b25759542'
};
exports.error = {
    0: ['the cluster is de-initializing', 'the cluster is re-initializing', 'the cluster is rollbacking'],
    1: 'the cluster is not initialized',
    2: 'the cluster has been initialized',
    11: 'no key or wrong key',
    12: 'gzip response body error',
    21: 'get the cluster status error',
    22: 'connect to mongodb error',
    31: 'check the cluster initialization environment error',
    32: 'get raid recommended configuration error',
    33: 'get disk list error',
    41: 'initialize the cluster error',
    42: 'de-initialize the cluster error',
    51: 'login error',
    52: 'get default user error',
    53: 'get user error',
    54: 'add user error',
    55: 'update user error',
    56: 'delete user error',
    61: 'get cluster info error',
    62: 'get metadata status error',
    63: 'get storage status error',
    64: 'get cluster target error',
    65: 'get cluster throughput error',
    66: 'get cluster iops error',
    67: 'get cluster node list error',
    71: 'get node service error',
    72: 'get node cpu error',
    73: 'get node memory error',
    74: 'get node throuphput error',
    75: 'get node iops error',
    76: 'get node target error',
    81: 'get cluster service and client error',
    82: 'add metadata service error',
    83: 'add storage service error',
    84: 'add management service error',
    85: 'add client error',
    91: 'get snapshot setting error',
    92: 'update snapshot setting error',
    101: 'get snapshot error',
    102: 'create snapshot error',
    103: 'update snapshot error',
    104: 'delete snapshot error',
    105: 'batch delete snapshot error',
    106: 'rollback snapshot error',
    121: 'get snapshot task error',
    122: 'create snapshot task error',
    123: 'update snapshot task error',
    124: 'enable snapshot task error',
    125: 'disable snapshot task error',
    126: 'delete snapshot task error',
    127: 'batch delete snapshot task error',
    131: 'get client error',
    132: 'get nas server error',
    133: 'add nas server error',
    134: 'update nas server error',
    141: 'get nfs share error',
    142: 'create nfs share error',
    143: 'update nfs share error',
    144: 'delete nfs share error',
    145: 'batch delete nfs share error',
    146: 'get client from nfs hsare error',
    147: 'add client to nfs hsare error',
    148: 'update client in nfs hsare error',
    149: 'delete client in nfs hsare error',
    151: 'get cifs share error',
    152: 'create cifs share error',
    153: 'update cifs share error',
    154: 'delete cifs share error',
    155: 'batch delete cifs share error',
    156: 'get user and group from cifs hsare error',
    157: 'add user and group to cifs hsare error',
    158: 'update user and group in cifs hsare error',
    159: 'delete user and group in cifs hsare error',
    151: 'get nas export error',
    152: 'create nas export error',
    153: 'update nas export error',
    154: 'delete nas export error',
    161: 'get local auth user error',
    162: 'create local auth user error',
    163: 'update local auth user error',
    164: 'delete local auth user error',
    165: 'batch delete local auth user error',
    171: 'get local auth user group error',
    172: 'create local auth user group error',
    173: 'update local auth user group error',
    174: 'delete local auth user group error',
    175: 'get local auth user from group error',
    176: 'add local auth user to group error',
    177: 'remove local auth user from group error',
    181: 'create target error',
    182: 'get buddy group error',
    183: 'create buddy group error',
    191: 'get file error',
    192: 'get entry info error',
    193: 'set pattern error',
    201: 'get event log error',
    202: 'get audit log error',
    211: 'run snapshot task error',
    212: 'run send change password message task error'
};
exports.event = {
    1: 'de-initialize cluster start',
    2: 'de-initialize cluster end',
    3: 're-initialize cluster start',
    4: 're-initialize cluster end',
    11: 'create snapshot start',
    12: 'create snapshot end',
    13: 'delete snapshot successfully',
    14: 'delete snapshot failed',
    15: 'batch delete snapshot successfully',
    16: 'batch delete snapshot failed',
    17: 'rollback snapshot start',
    18: 'rollback snapshot end',
    21: 'change admin password'
};
exports.i18n = {
    admin: '管理员',
    successfully: '成功',
    failed: '失败',
    login: '登录',
    logout: '登出',
    create: '创建',
    add: '添加',
    update: '更新',
    delete: '删除',
    remove: '移除',
    from: '从',
    to: '向',
    in: '在',
    user: '用户',
    snapshot: '快照',
    setting: '设置',
    batch: '批量',
    rollback: '回滚',
    schedule: '任务',
    enable: '启动',
    disable: '关闭',
    share: '共享',
    client: '客户端',
    local: '本地',
    authentication: '认证',
    group: '组',
    event: '事件',
    log: '日志',
    directory: '目录',
    pattern: '条带',
    or: '或者',
    server: '服务器',
    target: '目标',
    buddy: '伙伴',
    cluster: '集群',
    metadata: '元数据',
    storage: '存储',
    management: '管理',
    service: '服务'
};